env:
  browser: true
  es2021: true
extends:
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
